export const endpoints = {
    root: 'https://localhost:44343/api',
    ecoEndpoints: {
        get: 'Eco/Get',
        getAsync: 'Eco/GetAsync',
        getAll: 'Eco/GetAll',
        getAllAsync: 'Eco/GetAllAsync',
        getDetailsDto: 'Eco/GetDetails',
        getDetailsDtoAsync: 'Eco/GetDetailsAsync',
        add: 'Eco/Add',
        addAsync: 'Eco/AddAsync',
        update: 'Eco/Update',
        updateAsync: 'Eco/UpdateAsync',
        updateEcoStage: 'Eco/UpdateEcoStage',
        delete: 'Eco/Delete',
        deleteAsync: 'Eco/DeleteAsync',
    },
    ecoTagEndpoints: {
        get: 'EcoTags/Get',
        getAsync: 'EcoTags/GetAsync',
        getAll: 'EcoTags/GetAll',
        getAllAsync: 'EcoTags/GetAllAsync',
        add: 'EcoTags/Add',
        addAsync: 'EcoTags/AddAsync',
        update: 'EcoTags/Update',
        updateAsync: 'EcoTags/UpdateAsync',
        delete: 'EcoTags/Delete',
        deleteAsync: 'EcoTags/DeleteAsync',
    },
    ecoTypeEndpoints: {
        get: 'EcoTypes/Get',
        getAsync: 'EcoTypes/GetAsync',
        getAll: 'EcoTypes/GetAll',
        getAllAsync: 'EcoTypes/GetAllAsync',
        add: 'EcoTypes/Add',
        addAsync: 'EcoTypes/AddAsync',
        update: 'EcoTypes/Update',
        updateAsync: 'EcoTypes/UpdateAsync',
        delete: 'EcoTypes/Delete',
        deleteAsync: 'EcoTypes/DeleteAsync',
    }
};
